add descriptions of various mailing lists
hacsoc/wiki pull request #27
Opened 2016-02-26 22:52 UTC by ajm188

very open to feedback here.

bringing in at least @timtadh @matthewbentley @brenns10 @k4therin2 for discussion

2016-02-26 22:55 UTC, matthewbentley commented on organizational/communications.rst
>        <https://lists.case.edu/wws/info/hackers-summer>`_
Oops

2016-02-26 22:55 UTC, ajm188 commented on organizational/communications.rst
>        <https://lists.case.edu/wws/info/hackers-summer>`_
lol. `git blame`

2016-02-28 20:05 UTC, matthewbentley commented
Add hacsoc-officers

2016-02-28 20:06 UTC, zwh2 commented on organizational/communications.rst
> +      This list is probably not moderated.
Can we figure out if this is or isn't moderated.

2016-02-28 20:09 UTC, zwh2 commented
Can we just delete all of lists that are "a relic from an earlier time"

2016-10-01 21:27 UTC, thomasrussellmurphy requested changes
While this may need more work, having a good place to start from would be great, particularly since this hasn't gotten very far. @ajm188 can you address talking about Google Groups in the future, then see if we can merge this?

2016-10-01 21:27 UTC, thomasrussellmurphy commented on organizational/communications.rst
>  - Has to move over to some Google hosted service before the end of 2015?
Change this to "the most used lists will be migrated to Google Groups and others may be deleted"?

2016-10-02 02:22 UTC, ajm188 commented on organizational/communications.rst
>  - Has to move over to some Google hosted service before the end of 2015?
Yeah I'll update in a sec. Boy howdy, I wish you could "request changes" as a diff, and then I could click a button that applied them... 😛

2016-10-02 02:29 UTC, thomasrussellmurphy approved these changes

2016-10-02 02:29 UTC, thomasrussellmurphy commented
Features! I'm going to merge this.

2016-10-02 02:30 UTC, merged

2016-10-02 02:30 UTC, ajm188 commented
beat ya :)

2016-10-02 02:31 UTC, thomasrussellmurphy commented
Aww. I was going to try squash+merge, but too late.

2016-10-02 02:32 UTC, ajm188 commented
Call me old fashioned, but I like my `--no-ff` merges